[features]
seeds = false
[programs.devnet]
buildspace_project = "DUrx4ePymCTDArf4msxweYfRsZKbrjDqD9ELgjSTdoBG"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/threedevx/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
